### PR TITLE
Add Turkish Translation (#430)

### PR DESCRIPTION
**Pull request by FurkanS1821**
Added Turkish translation.

I wasn't able to test this, so beware before merging.

### CODE REVIEW

**Comment by FurkanS1821** [comment]
Ouch, forgot to escape some of the `'`

**Comment by corbinlc** [comment]
Do you know anyone who could review your work?  I don't speak Turkish and no one on the team does to my knowledge

**Comment by FurkanS1821** [comment]
> Do you know anyone who could review your work? I don't speak Turkish and no one on the team does to my knowledge

Well, nope. I don't have so many friends. Sorry.

**Comment by corbinlc** [comment]
Ok, I will try it out and check some of the translations in google translate.  It will take me a bit.

**Comment by corbinlc** [comment]
I have spot checked this.  Obviously would appreciate anyone's feedback on this later.

**Comment by corbinlc** [comment]
@FurkanS1821 thanks!

**Pull request merged**
