### PR TITLE
Translation of strings.xml in Portuguese (BR)

### PR DESCRIPTION
**Pull request by thezakman**
**Describe the pull request**

Portuguese (Brazilian) translation of strings.

**Link to relevant issues**

Issue #430 Translations needed

### CODE REVIEW

**Comment by thezakman** [comment]
https://github.com/CypherpunkArmory/UserLAnd/issues/430#issuecomment-485642079

**Comment by corbinlc** [comment]
@thezakman Please notice this error in the build log:
```
> Task :app:mergeDebugResources FAILED
/home/circleci/workspace/app/src/main/res/values-pt-BR: Error: Invalid resource directory name

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:mergeDebugResources'.
> /home/circleci/workspace/app/src/main/res/values-pt-BR: Error: Invalid resource directory name
```

**Comment by corbinlc** [comment]
Probably want, `values-pt-rBR` instead of `values-pt-BR`.  Please try that out.

**Comment by thezakman** [comment]
Ok, ill push it now.

**Comment by thezakman** [comment]
@corbinlc still got error with "values-pt-rBR"

**Comment by corbinlc** [comment]
The error is different this time.  You now have the filed named correctly.
```
> Task :app:mergeDebugResources FAILED
/home/circleci/workspace/app/src/main/res/values-pt-rBR/strings.xml:61:39: Error: Element type "string" must be followed by either attribute specifications, ">" or "/>".

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:mergeDebugResources'.
> /home/circleci/workspace/app/src/main/res/values-pt-rBR/strings.xml:61:39: Error: Element type "string" must be followed by either attribute specifications, ">" or "/>".
```

**Comment by corbinlc** [comment]
You have a syntax issue on line 61

**Comment by corbinlc** [comment]
`<string name="illegal_state_title"UserLAnd entrou em um estado ilegal!</string>`
should probably be
<string name="illegal_state_title">UserLAnd entrou em um estado ilegal!</string>

**Comment by corbinlc** [comment]
Please click on a failing build where it says "Details" to see the same errors I am seeing.

**Comment by thezakman** [comment]
@corbinlc my bad, that is true.
Will fix it now.

**Comment by thezakman** [comment]
Done ;)

**Comment by corbinlc** [comment]
Do you think this translation would work pretty well for Portuguese speakers in other places outside of Brazil?

**Comment by thezakman** [comment]
@ corbinlc, will work 90% since European Portuguese (Portugal) differs somewhat from ours (not much though).

**Comment by corbinlc** [comment]
I was just thinking we could make this the `values-pt` file instead of the `values-pt-rBR` file and help people outside of Brazil too.  Then, we would only create a `values-pt-r*` for differences that people flag.  What do you think?

**Comment by thezakman** [comment]
It is better to keep European Portuguese as a standard and use values-pt-rBR ​​for Brazilians, since it is used not only in Portugal but also in other countries in Africa.

**Comment by corbinlc** [comment]
We just don't have any European Portuguese translation so far.

**Comment by thezakman** [comment]
So if you think would be better to keep this format, go for it :)

**Review by corbinlc — APPROVED** [review]
All looks good now.  Obrigado.

**Comment by corbinlc** [comment]
This will go out in our next release.

**Comment by thezakman** [comment]
No problem man, i'm glad I could help. 
Cheers!

**Comment by hugok79** [comment]
> We just don't have any European Portuguese translation so far.

@corbinlc I can help with the European Portuguese translation. (pt, pt_PT)

**Review by c06840807-create — APPROVED** [review]

**Comment by c06840807-create** [comment]
Thanls

**Review by c06840807-create — APPROVED** [review]

**Pull request merged**
