### PR TITLE
Add crashlytics logging.

### PR DESCRIPTION
**Pull request by MatthewTighe**
**Describe the pull request**

This adds crashlytics logging. This will allow us to have better snapshots of app state when crashes occur. It is dependent on an api key and build secret which have not been included in the PR.

**Link to relevant issues**
N/A

### CODE REVIEW

**Comment by EnderNightLord-ChromeBook** [comment]
Thats A Good Idea... How are you going to get the api key?

**Comment by MatthewTighe** [comment]
It will be shared between members of our team.

**Comment by relan** [comment]
FYI, UserLAnd won't get any updates on F-Droid after this change because Crashlytics is proprietary software. https://f-droid.org/en/docs/Inclusion_Policy/

**Comment by EnderNightLord-ChromeBook** [comment]
Why Do You Use F-Droid As Well? Doesn't Most People Use The Playstore?

**Pull request merged**
