### PR TITLE
Add Polish translation

### PR DESCRIPTION
**Pull request by BxOxSxS**
**Describe the pull request**
Polish translation of strings.

**Link to relevant issues**
Issue #430 Translations needed

### CODE REVIEW

**Comment by corbinlc** [comment]
I am so sorry to get back to you so slowly.  I didn't see this.  This is great.  Do you know another github user who can review this?  I wouldn't be able to provide proper feedback.

**Comment by BxOxSxS** [comment]
Unfortunately, I don't know anyone who could confirm my translation

**Comment by corbinlc** [comment]
I will just merge it and let people tell me if there are any changes needed later.

**Comment by eslam772** [comment]
[proot.txt](https://github.com/user-attachments/files/19260094/proot.txt)

**Review by Bajbus87aik — CHANGES_REQUESTED** [review]
Ok danke

**Review by Bajbus87aik — COMMENTED** [review]
Oksuper

**Review by Yang062 — APPROVED** [review]

**Pull request merged**
