### PR TITLE
Korean Translation

### PR DESCRIPTION
**Pull request by dolphin2410**
Added Korean translation

### CODE REVIEW

**Comment by corbinlc** [comment]
I am getting back to this project now.  Do you know another Korean speaker who can review your work?

**Comment by angrymusic** [comment]
Hello, I'm a passing Korean. May I review this work?

**Comment by dolphin2410** [comment]
> Hello, I'm a passing Korean. May I review this work?

Of course. Thanks!

**Comment by angrymusic** [comment]
plz check my reviews :)

**Review by rudra1122 — APPROVED** [review]

**Pull request closed without merging**
