### PR TITLE
Add Desktop Photos To Google Play

### PR DESCRIPTION
**Pull request by EnderNightLord-ChromeBook**
Kali Lxde desktop (1) and ubuntu lxde desktop (2)

### CODE REVIEW

**Comment by MatthewTighe** [comment]
@corbinlc Is this how this works?

**Comment by corbinlc** [comment]
@MatthewTighe  Right now we have no flow for using the contents directly from github for the Play Store listing.  There are some tools for doing so, but I haven't researched them yet.  I am fine with those files being in this new subdirectory for now, until we figure out how to put all the play store info in the repo.

**Comment by EnderNightLord-ChromeBook** [comment]
right I'll have a look too...

**Comment by EnderNightLord-ChromeBook** [comment]
Added Debain Lxde Desktop

**Comment by corbinlc** [comment]
Here is the article I read about what f-droid supports for it pulling in an apps listing automatically.  Some of the tools mentioned are for publishing the same info to the Play Store.  I have not looked further into this and don't have a specific recommendation right now.  
https://f-droid.org/en/docs/All_About_Descriptions_Graphics_and_Screenshots/

**Comment by EnderNightLord-ChromeBook** [comment]
Ok I Found Out How It Works...

**Comment by MatthewTighe** [comment]
@EnderNightLord-ChromeBook Can you update this to use the directory structure used in #466 ?

**Comment by EnderNightLord-ChromeBook** [comment]
> @EnderNightLord-ChromeBook Can you update this to use the directory structure used in #466 ?

Yes matt...

**Comment by EnderNightLord-ChromeBook** [comment]
I may need to do this again... I accidentally deleted the fork...

**Pull request closed without merging**
