### PR TITLE
German translation

### PR DESCRIPTION
**Pull request by RudiAusBuddeln**
The German language has both a formal and informal salutation. I opted in to the formal one; however the informal one can be used in an app as well. Most apps just try to not use either.

### CODE REVIEW

**Comment by corbinlc** [comment]
Thanks!  This is much appreciated.

Did you manually test this?  I have not, but certain syntax errors in the .xml files can cause the app to crash when the given language is used.  

Know any other German speakers on github who would like to review the translations?

**Comment by RudiAusBuddeln** [comment]
No, I did not manually test this (I have never coded an Android app before). And maybe @MoriPastaPizza would try to check this? I do not know anyone personally though.

**Comment by TaTaRsKiY059** [comment]
Update

**Comment by corbinlc** [comment]
@pp-sepag or @th-sepag any interest in reviewing this translation?  I know only like 5 words in German.  If you open strings.xml in AndroidStudio there is a view where it will show you the default/English next to all of the translations that have been provided.

**Comment by pp-sepag** [comment]
We reviewed and modified the translation, see commit 37403a7. I did test it manually, it seems OK. Should I open a new pull request?

**Comment by corbinlc** [comment]
@pp-sepag Yes that would work well.  @RudiAusBuddeln feel free to compare and comment on the new commit.

**Comment by RudiAusBuddeln** [comment]
Closing this as #1364 has been merged.

**Pull request closed without merging**
