### PR TITLE
Create Unsupported / Broken-Devices List 

### PR DESCRIPTION
**Pull request by EnderNightLord-ChromeBook**
**Describe the pull request**
This will show what devices work with userLAnd and what don't for the time being

### CODE REVIEW

**Comment by corbinlc** [comment]
I don't want to commit to creating or maintaining this list.  Maybe we should do the inverse and add a known issues?  Right now I am happy with just adding regular issues if UserLAnd doesn't work for a given device, but I don't think we have found one where it just doesn't work at all.  Are you seeing some devices this does not work for?

**Comment by corbinlc** [comment]
That is the true, the Huawei phones have many issues do to broken POKE_DATA functionality.  I will handle this by creating one summary issue that covers what devices are impacted and what has been done and what the remaining issues are.

**Comment by EnderNightLord-ChromeBook** [comment]
Cool Sounds Good I Will Edit My .txt File

**Comment by EnderNightLord-ChromeBook** [comment]
Does The Huawei 3i Work? Do You Know?

**Comment by MatthewTighe** [comment]
We just don't have the resources to maintain a list like this. Additionally, it can be hard to tell from user reports whether the app is broken because of their device or because of some interaction with the app. This kind of list would also be better placed in the wiki rather than as a somewhat random asset in the repo itself.

Feel free to open an issue requesting this kind of list be added to the wiki if you'd like it to happen eventually, but for now I'm going to close this PR.

**Pull request closed without merging**
